repos:
  # Ruff: Fast Python linter + formatter
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 4f1f84f27e5e694155dd8d2781527e8f7a1d1f95  # ruff-pre-commit@v0.4.4
    hooks:
      - id: ruff
        args: ["--fix"]  # Automatically fix issues

  # Prettier: Formatter for JS, JSON, CSS, etc.
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 394a826d5c4ee9a85a31f9b24d4e03269e0c7b01  # mirrors-prettier@v3.1.0
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.2.5  # Explicit version of Prettier to use
