repos:
  # Ruff: Fast Python linter
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.287  # Use the specific version you need
    hooks:
      - id: ruff
        args: ["--fix"]  # Auto-fix linting issues when possible

  # Black: Python code formatter
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

  # isort: Automatically organize imports
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]  # Match Black's import style

  # Pre-commit hooks for common issues
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Ensure this is updated to resolve deprecation warnings
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml

  # Flake8: Use the PyPI mirror to avoid GitLab authentication issues
  - repo: https://github.com/pre-commit/mirrors-flake8
    rev: v6.1.0
    hooks:
      - id: flake8
