repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.8  # Replace with the desired version tag
    hooks:
      - id: ruff
        args: ["--fix"]


  # Prettier: Formatter for JS, JSON, CSS, etc.
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 394a826d5c4ee9a85a31f9b24d4e03269e0c7b01  # mirrors-prettier@v3.1.0
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.2.5  # Explicit version of Prettier to use
