repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.8  # Replace with the desired version tag
    hooks:
      - id: ruff
        args: ["--fix"]


  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0  # Replace with the desired version tag
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.2.5  # Specify the Prettier version you want to use
