name: Fix Linting on Request

on:
  issue_comment:
    types: [created]  # Trigger on new comments

jobs:
  fix-linting:
    if: >
      github.event.issue.pull_request != null &&
      contains(github.event.comment.body, '@github-bot fix linting')
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the PR branch
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.issue.pull_request.head.ref }}  # Checkout the PR branch

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Step 3: Install Ruff
      - name: Install Ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      # Step 4: Run Ruff to Fix Linting Issues
      - name: Run Ruff Auto-fix
        run: |
          ruff --fix .

      # Step 5: Commit Auto-Fixes
      - name: Commit Changes
        run: |
          git config --global user.name "github-bot"
          git config --global user.email "github-bot@example.com"
          git add .
          git commit -m "fix: Auto-fix linting issues via Ruff"
        continue-on-error: true  # Skip the commit step if no changes were made

      # Step 6: Push Changes Back to the PR Branch
      - name: Push Changes
        run: git push
