name: Pre-Commit

on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  pre-commit:
    name: Run Pre-Commit Hooks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Pre-Commit and Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Run Pre-Commit Hooks
        id: precommit
        run: |
          pre-commit run --all-files --show-diff-on-failure 2>&1 | tee pre-commit-output.log
        continue-on-error: true

      - name: Upload Pre-Commit Logs (if failure)
        if: failure()
        uses: actions/upload-artifact@v3 # Ensure this is correctly specified
        with:
          name: pre-commit-logs
          path: pre-commit-output.log
