name: Pre-Commit Hooks

on:
  pull_request:    # Runs on pull requests
  push:            # Also runs on pushes
    branches:
      - main       # Adjust to your main branch
      - dev        # Add other branches as necessary

jobs:
  pre-commit:
    name: Run Pre-Commit Hooks
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"  # Match your project's Python version

      # Step 3: Install dependencies
      - name: Install pre-commit and Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      # Step 4: Install and Run Pre-Commit Hooks
      - name: Run Pre-Commit Hooks
        run: pre-commit run --all-files --show-diff-on-failure
