name: Pre-Commit

on:
  pull_request:  # Runs on pull requests
  push:          # Run check on pushes too
    branches:
      - main    # Adjust to your default/main branch
      - dev     # Add other branches as necessary

jobs:
  pre-commit:
    name: Run Pre-Commit Hooks
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"  # Use the Python version supported by your project

      # Step 3: Install dependencies for pre-commit
      - name: Install Pre-Commit and Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      # Step 4: Run Pre-Commit Hooks and Save Results
      - name: Run Pre-Commit Hooks
        id: precommit
        run: |
          pre-commit run --all-files --show-diff-on-failure 2>&1 | tee pre-commit-output.log
        continue-on-error: true # Prevent the job from immediately failing so we can annotate errors

      # Step 5: Annotate Issues in GitHub (Optional for Explicit Feedback)
      - name: Annotate Errors
        if: failure()
        run: |
          echo "::group::Annotating pre-commit errors"
          while IFS= read -r line; do
            # Format the pre-commit output as GitHub error annotations
            if [[ $line == *"[ERROR]"* ]]; then
              file=$(echo "$line" | grep -oP "^[^:]+")
              lineno=$(echo "$line" | grep -oP ":[0-9]+" | head -1 | tr -d ':')
              error=${line##*: }
              echo "::error file=${file},line=${lineno}::${error}"
            fi
          done < pre-commit-output.log
          echo "::endgroup::"

      # Step 6: Upload Logs for Debugging
      - name: Upload Pre-Commit Logs (if failure)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: pre-commit-logs
          path: pre-commit-output.log
        
      # Step 7: Fail the Job if Pre-Commit Hooks Fail
      - name: Fail the Job Explicitly
        if: failure()
        run: |
          echo "Some pre-commit hooks failed."
          exit 1
