name: Pre-Commit Hooks

on:
  pull_request:  # Run on pull requests
  push:          # Run on pushes as well
    branches:
      - main    # Main branch
      - dev     # Add additional branches if necessary

jobs:
  pre-commit:
    name: Run Pre-Commit Hooks
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"  # Specify the Python version your repository is using

      # Step 3: Install pre-commit and dependencies
      - name: Install Pre-Commit and Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      # Step 4: Initialize and Run Pre-Commit Hooks
      - name: Run Pre-Commit Hooks
        run: pre-commit run --all-files --show-diff-on-failure
