name: Pre-Commit Hooks

on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  pre-commit:
    name: Run Pre-Commit Hooks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run Pre-Commit Hooks
        uses: pre-commit/action@v4
        with:
          extra_args: --color=always --show-diff-on-failure
